image: mcr.microsoft.com/dotnet/sdk:6.0

stages:          
  - build
  - test
  - pack
  - publish

build-job:       
  stage: build
  script:
    - dotnet build ./RaroNotifications/RaroNotifications.sln -c Release
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - ./RaroNotifications/bin/
      - ./RaroNotifications/obj/

unit-test-job:   
  stage: test    
  script:
    - dotnet test ./RaroNotifications/

publish-job:
  stage: publish
  script:
    - dotnet nuget push ./RaroNotifications/bin/Release/*.nupkg --api-key $NUGET_API --source https://api.nuget.org/v3/index.json
  dependencies:
    - build-job
  only:
    - main
