image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:          
  - build
  - test
  - pack
  - publish

build-job:       
  stage: build
  script:
    - dotnet build ./RaroNotifications/-c Release

unit-test-job:   
  stage: test    
  script:
    - dotnet test ./RaroNotifications/

pack-job:      
  stage: pack  
  script:
    - dotnet pack ./RaroNotifications/ -c Release

publish-job:
  stage: publish
  script:
    - dotnet nuget push "./RaroNotifications/bin/Release/*.nupkg" --api-key $NUGET_API --source https://api.nuget.org/v3/index.json
  only:
    - main
